### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [syko/SublimeGotoUsage#2]
Hi
i see it is good plugin, on  which engine it is based? Can it be ported to Cudatext (if it is some library based)?

**Comment by syko** [comment]
It's not based on any engine per-se, only sublime own API and custom parsing of text files.
Seems that Cudatext has a python API so it should be very possible to port this over.

The api that is required from Cudatext would be:
- showing some sort of list where the user can pick an item
- opening other files
- selecting text + scrolling to a certain spot within the file
- running other plugin commands
- loading some sort of user-customizable settings file for the plugin
- optionally showing some status messages and such

I probably will not port this myself as I'm unfamiliar with Cudatext and its API and don't use it myself and I don't really have the time for it right now but feel free to have a crack at it!
If you grep the codebase for `sublime` you should find all the calls to the Sublime API. Everything else uses only python 3 standard lib and should work out-of-the box.

**Comment by Alexey-T** [comment]
Ok..Can src be made nicer to "port to Cuda"? e.g. make def's /class's which donot depend on ST (then ST3 uses these def's)
